### ISSUE TITLE
Error: Cannot find module "./build" after starting the browser

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#688]
Started happening I believe after https://github.com/mozilla/tofino/pull/654

Errors show up in the browser console.

@Mossop ping

**Comment by victorporof** [comment]
I'm also getting 
```
/Users/victorporof/Work/Mozilla/tofino/.electron/Electron.app/Contents/Resources/electron.asar/rend…:130 Unable to load preload script: /Users/victorporof/Work/Mozilla/tofino/lib/shared/preload/content.js
```

We're injecting shared/preload/content.js in page.jsx. This also stopped working after #654.

@Mossop try deleting your lib folder and rebuilding.

**Comment by Mossop** [comment]
Ah I see it now. But it's in the developer tools not the browser toolbox.

**Comment by jsantell** [comment]
We talked about this yesterday, but this is from `bunyan` including dtrace, which is an optional dependency that gets installed since it's used on our main process, but in the webpacked UI version, it can't be 'browserified'. There doesn't appear to be any actual breakage from this, however

**Comment by Mossop** [comment]
This might be fixable with some additions to the webpack config: https://github.com/trentm/node-bunyan#webpack

**Comment by jsantell** [comment]
The above fix doesn't seem to work, as the dtrace provider is still installed, so bunyan thinks it exists, and was installed optionally, getting an error like:

`webpack:///./~/bunyan/lib/bunyan.js?:443 Uncaught TypeError: dtrace.createDTraceProvider is not a function`

We could stub out all methods, but that won't trick Bunyan into not calling it at all
